# Source: https://drupalize.me/series/drupal-development-docker
# Here you specify the version of the docker-compose
version: '3'
services:
  # The key is the service name.
  <SERVICE_NAME>:
    image: imageName
    # List of path mapping from Host OS to Container.
    volumes:
      # The best practice is to use relative paths for the source(host OS) path,
      # and an absolute path for the target(container) path.
      - /path/on/host:/path/on/guest
      # There are 3 types of synchronization strategy and they are:
      #  faster
      #    ^
      #    |    1. Delegated (delegated) |
      #    |    2. Cached (cached)       |
      #    |    3. Consistent (default)  |
      #                                  v
      #                                safer
      # Ex:
      #   - ./docroot:/var/www/html:cached
      - /path/on/host:/path/on/guest:<SYNC_STRATEGY>
    # We can set static values as environment variables in the this file
    # using the `environment` key.
    environment:
      <VARIABLE_NAME>: <VALUE>
      # Another way to specify variable definition is using the shell format
      # as follows:
      # Ex:
      #    - <VARIABLE_NAME>=<VALUE>
      - <VARIABLE_NAME>=<VALUE>
    # With `env_file` key you can specify the file from which to read variable
    # names and values.
    # It can take one or more file paths.
    # Use this when you want to use the same environment variables on multiple
    # containers.
    env_file:
      - ./mysql.settings
    # Use the `ports` key to expose the container's port.
    ports:
      - 80
      - 443
      # We can also map ports from Host OS to container as follows:
      #   portOnHost:portInContainer
      #
      # The following port mapping maps the port 8080 on the Host OS to the
      # port 80 on the container.
      #
      # Note: Always use port mappings if possible, even if the port numbers
      # are the same.
      - "8080:80"
